Surnet/swagger-jsdoc

lib/index.js
I'd like to use swagger-jsdoc together with a PHP-Project. Since the documentation style is similar in many programming languages, I removed the restriction for the file extension "*.js".
=> Removed filename restriction for "*.js"

.jshintrc, example/app.js, example/parameters.yaml, example/routes.js, lib/index.js, test/swagger-spec.json
Document responses, parameters and securityDefinitions in a similar fashion as for definitions.
Able to include directly yaml files as apis (that will be merged with the jsdoc comments).
Tests included, but increased max statements from 15 to 18 and max complexity from 6 to 8 to pass the jshint test.
=> Include .yaml, and able to define responses, parameters and securityDefinitions

lib/index.js
path.parse is not present in node 0.10.x
this change allows to use swagger-jsdoc with node 0.10.x
=> use path.extname instead of path.parse

.jshintrc, example/app.js, example/routes2.js, lib/index.js, package.json, test/swagger-spec.json
Re: #19
This is my first pass at the glob feature. Since the `glob` library handles non-glob strings perfectly fine, I simply map-reduce the whole `apis` array through glob, and then pass the resulting array into the for-loop.
Tests still pass, but I'm not sure if a spec was written for this part of the code.
=> [WIP] options.api allows glob strings

.jshintrc, example/routes.js, lib/index.js, test/swagger-spec.json
Added swagger tags support, will fix #22.
Note the I had to slightly tweak JSHint config, let me know if that is not an option.. Otherwise I will have to rewrite/split `addDataToSwaggerObject()` to overcome maxcomplexity/maxstatements rules.
=> Add swagger tags support

.jshintrc, example/routes.js, lib/index.js, test/swagger-spec.json
Allow to set multiple tags in jsdoc with as an array
It will allow definition of tags in swagger definition and will merge with others in the jsdoc.
=> support multiple tags as an array and in definition

lib/index.js
Only setting properties on the swaggerObject that do not exist to prevent overwriting user specified properties.
=> Don't override user provided swagger definition options

example/app.js, example/parameters.yaml, example/routes.js, lib/index.js, lib/swagger-helpers.js, package.json, test/fixtures/swaggerObject.json, test/fixtures/testData.js, test/swagger-helpers-test.js
Relates to #38
Updates example files with plural version of properties, while handling both singular and plural.
Currently refactoring definition/definitions and parameter/parameters to solve an open issue.
Yet, the function to parse properties is now placed into a separate module to be testable.
Also, properties "categorization" of deprecated vs correct is done in order to easily continue the refactoring, i.e. there are further properties to be handled: [properties](https://github.com/OAI/OpenAPI-Specification/blob/master//versions/2.0.md#fixed-fields)
=> Revising input swagger properties

README.md
I had to spend quite some time to figure out what was wrong with my code. Apparently, the sample had a deprecated property `definition`, now should be`definitions`
=> Updating sample to comply with Swagger v2

bin/swagger-jsdoc.js, package.json
This is upgrading outdated modules, as reported by https://gemnasium.com/Surnet/swagger-jsdoc
=> chore(dependencies): update modules

example/routes.js, lib/swagger-helpers.js, test/cli-test.js, test/fixtures/deprecated_routes.js, test/swagger-spec.json
References issue #44
Ignores deprecation checks if property is a direct child of a 'properties' object.
=> Ignore deprecation check

README.md, bin/swagger-jsdoc.js, test/cli-test.js
Basically adds support for `./bin/swagger-jsdoc -o output.yaml`.
=> Add CLI support for YAML output

README.md, bin/swagger-jsdoc.js, example/app.js, example/routes.js, example/routes2.js, example/swaggerDef.js, lib/swagger-helpers.js, package.json, test/cli-test.js
This suggestion improves the use of the CLI tool, providing a watch task on input files containing API documentation, updating the end specification on change.
The main aim being to simplify integration with browsersync and swagger-ui making workflow (documentation -> testing -> development) process easier.
Notes:
- Default output specification file is renamed to be swagger.json as of [specification convention](http://swagger.io/specification/#file-structure-11).
- Input definition file is not under watch task, because `require` cache. I tried to work around the cache in order to make it possible, but I couldn't. In the end, I think it's more important to keep this part simpler (`.json` or `js` file being possible inputs) and having in mind that this file is usually static and small.
- …
=> Include watch task in cli tool.

.npmignore
New entry in the npm ignore file to exclude hidden cloud9 folder on `npm publish` command.
=> Ignore c9 hidden folder on npm publish

bin/swagger-jsdoc.js, docs/CLI.md, test/cli-test.js, test/fixtures/api_definition.js
This should add the ability to use the `api` key definition in the definitions file to read file sources for APIs.
=> Adding support for APIs in definition file.

README.md, lib/swagger-helpers.js, test/swagger-helpers-test.js
This pull request should fix the swagger output object to not include custom option keys. Specifically added a `blacklist` of keys to not include in the output object for maintainability for future options that may be added.
* Added and updated tests
* Added excluded list for key definitions that are to be removed
=> Remove invalid swagger keys from swagger output object

bin/swagger-jsdoc.js, docs/CLI.md
The correct key name is `apis`, not `api`.
=> Fix apis name in CLI docs and error message

docs/GETTING-STARTED.md
Obviously left over when copy/pasting from previous example, the description was wrong and didn't match what the route does.
=> Fix misleading description

package.json
This fixes half of #100
The other half depends on `fsevents`. They fixed the problem 2 weeks ago but they haven't released to `npm` yet.
=> Upgrade chokidar 1.7.0 -> 2.0.3

lib/helpers/specification.js, package.json, yarn.lock
While reviewing #106 I found that there is no more deprecation message functionality, only the correction one.
=> refactor(helpers): remove unused functions

docs/GETTING-STARTED.md
This PR makes clear in the GETTING-STARTING.md documentation that the default specification is swagger 2.0.
=> Adding specification configuration documentation to GETTING-STARTED.md

bin/swagger-jsdoc.js
When an `apis` property is used in the `swaggerDef.js`, it propagates to the generated `swagger.json`. Because `apis` is not a valid OpenAPI property, it does not pass Swagger's validation.
`program.args` is specified as the `apis` argument to the `createSpecification` function thus we are safe to delete it from the `swaggerDefinition` at this point.
Current
Requested
=> Removes apis property from swaggerDefinition.

package.json
There is a vulnerability in 3.13.0.
I made a simple change but would suggest to accept wildcards for dependencies to be able to automatically solve these.
=> Updating js-yaml dependency to 3.13.1 to fix remote execution vulnerability

README.md
Update JSDoc's new domain name
=> fix: JSDoc Official website link

package.json, yarn.lock
I upgraded some development dependencies. All test passed with `yarn test` and `yarn test:lint`.
=> Update outdated dev dependencies

package.json, yarn.lock
I upgraded `swagger-parser` dependency. All test passed with `yarn test` and `yarn test:lint`.
It will fix the security issue for `js-yaml`.
=> Update swagger-parser to fix remote execution bug

README.md, lib/helpers/finalizeSpecificationObject.js, lib/helpers/getSpecificationObject.js, lib/helpers/parseApiFile.js, lib/helpers/parseApiFileContent.js, lib/helpers/updateSpecificationObject.js, lib/index.js
Hello,
I'm trying to use this module to create a webpack plugin that updates the swagger.json specification every time the code changes, but the way it is written now is not compatible with the way webpack works. In `getSpecificationObject`, it uses a glob pattern to read files on disk, while webpack will give me the file content in memory.
So this PR simply refactors the `parseApiFile` and `getSpecificationObject` functions and exposes other methods to handle the api files in memory as well as on disk. I avoided breaking changes, it still works the same way for the classic use case.
=> refactor(parser): expose specification builder methods

package.json, yarn.lock
Update commander version from 2.20.0 to 2.20.1
Hi! I realize this seems like a small change, but there is a vulnerability in commander 2.20.0 that is causing our build to "fail" :grin:
=> feat: update commander version

lib/index.js
Using swagger-jsdoc for the first time, I had trouble identifying that I wasn't passing the swaggerDefinition attribute.
With these changes it became more clearer the identification of the reported error.
=> Better describing errors

src/utils.js, test/utils.spec.js
Thank you for creating this! When extracting annotations and no doc strings are found, `match` returns `null`. When we try to iterate over the resulting `null`, we get a type error. This adds an empty array fallback to prevent that error and exit.
I thought about adding a warning that no docs were found here, though handling that in the caller seems more appropriate. Let me know if you'd prefer that to happen here!
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match#Return_value
=> Add empty array fallback to regex match

bin/swagger-jsdoc.js, docs/CLI.md, example/yaml-anchors-aliases/yaml-anchors-aliases.spec.js, package.json, src/specification.js, test/__snapshots__/cli.spec.js.snap, test/cli.spec.js, test/files/v2/api_definition.js, test/files/v2/api_definition.json, test/files/v2/api_definition.yaml
Fix the problem with not necessary `api` attribute inside the `swaggerDefinition` file:
Issue: https://github.com/Surnet/swagger-jsdoc/issues/233
=> Remove 'api' attr from swagger definition

bin/swagger-jsdoc.js, src/lib.js, src/specification.js, test/specification.spec.js
Closes https://github.com/Surnet/swagger-jsdoc/issues/237
=> fix: yaml export format

bin/swagger-jsdoc.js, test/__snapshots__/cli.spec.js.snap
Hi,
The CLI was still displaying a reference to the "apis" key when no source files were provided on the command line. I think the new message is more informative.
=> Issue with error message when using deprecated "apis" key

yarn.lock
The validator library has the below security issues. We need to upgrade to version 13.7.0 to resolve this. To do so, need to update swagger-parser to latest version and  hence all its dependencies are also updated.
Normally dependabot would create a PR for this, but it seems swagger-jsdoc is very far behind in a lot of dependencies and it may take a while before dependabot gets to this specific dependency. Creating this PR to at least avoid this security issue.
This commit was created by running `yarn upgrade swagger-parser`.
- https://nvd.nist.gov/vuln/detail/CVE-2021-3765
- https://github.com/validatorjs/validator.js/security/advisories/GHSA-xx4c-jj58-r7x6
=> fix: validator security update

.github/workflows/ci.yml
Publish changes to npm repository. Calling it a feat since from what I've seen in the commits, there's been features introduced worthy of a minor version bump.
=> feat: publish to npm for master branch

README.md
I found this option by accident when digging through the source. Therefore I wrote some docs about this flag and a use case where it would be useful.
=> docs: add section for failOnErrors option flag

package.json, yarn.lock
Fixes Vulnerability with dependency swagger-parser v10.0.2 #287.
swagger-parser depends on z-schema, which depends on validator, and the version that swagger-parser v10.0.2 depends on has a security vulnerability (https://github.com/advisories/GHSA-xx4c-jj58-r7x6).
PR #300 tried to fix this, but because the version is pinned to 10.0.2 exactly in package.json it hasn't changed the version used.
=> Upgrade swagger-parser to fix vulnerability
